import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '../lib/supabase';

const AppContext = createContext();

const SUPABASE_TABLE = 'bills';
const DEFAULT_HOUSE_ID = 'casa_1';

export const AppProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [ownerId, setOwnerId] = useState(null);
  const [houseId] = useState(() => {
    const params = new URLSearchParams(window.location.search);
    return (params.get('house') || DEFAULT_HOUSE_ID).trim().toLowerCase();
  });
  const [bills, setBills] = useState([]);
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [autoGeneratedCount, setAutoGeneratedCount] = useState(0);
  const [syncStatus, setSyncStatus] = useState('idle');

  // Authentication logic
  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) {
        setUser(session.user);
        setOwnerId(String(session.user.id));
      }
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => {
      if (session) {
        setUser(session.user);
        setOwnerId(String(session.user.id));
      } else {
        setUser(null);
        setOwnerId(null);
        setBills([]);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const storageKey = useCallback(() => {
    return ownerId ? `homehq_v4_${ownerId}_${houseId}` : `homehq_v4_${houseId}`;
  }, [ownerId, houseId]);

  // Sync with Supabase logic
  const syncToSupabase = useCallback(async (currentBills) => {
    if (!ownerId) return;
    setSyncStatus('syncing');

    const payload = currentBills.map(b => ({
      id: String(b.id),
      owner_id: ownerId,
      house_id: houseId,
      name: b.name,
      amount: Number(b.amount) || 0,
      due_date: b.dueDate,
      category: b.category,
      paid: !!b.paid,
      paid_at: b.paidAt || null,
      is_fixed: !!b.isFixed,
      is_installments: !!b.isInstallments,
      total_installments: Number(b.totalInstallments) || 0,
      current_installment: Number(b.currentInstallment) || 0
    }));

    if (payload.length > 0) {
      const { error: upsertError } = await supabase
        .from(SUPABASE_TABLE)
        .upsert(payload, { onConflict: 'id' });

      if (upsertError) {
        console.error('Error syncing to Supabase:', upsertError);
        setSyncStatus('error');
        return;
      }
    }

    // Handle deletions (sync local state with remote using soft delete)
    const { data: remoteRows } = await supabase
      .from(SUPABASE_TABLE)
      .select('id')
      .eq('owner_id', ownerId)
      .eq('house_id', houseId)
      .is('deleted_at', null);

    const localIds = new Set(currentBills.map(b => String(b.id)));
    const deleteIds = (remoteRows || []).map(r => String(r.id)).filter(id => !localIds.has(id));

    if (deleteIds.length > 0) {
      const { error: deleteError } = await supabase
        .from(SUPABASE_TABLE)
        .update({ deleted_at: new Date().toISOString() })
        .eq('owner_id', ownerId)
        .eq('house_id', houseId)
        .in('id', deleteIds);

      if (deleteError) {
        console.error('Error deleting:', deleteError);
        setSyncStatus('error');
        return;
      }
    }
    setSyncStatus('synced');
  }, [ownerId, houseId]);

  // Load bills logic
  useEffect(() => {
    if (!ownerId) {
      setBills([]);
      setIsDataLoading(false);
      return;
    }

    const loadData = async () => {
      setIsDataLoading(true);
      setSyncStatus('syncing');
      
      const { data, error } = await supabase
        .from(SUPABASE_TABLE)
        .select('*')
        .eq('owner_id', ownerId)
        .eq('house_id', houseId)
        .is('deleted_at', null)
        .order('due_date', { ascending: true });

      if (error) {
        console.error('Error loading bills:', error);
        const stored = localStorage.getItem(storageKey());
        if (stored) setBills(JSON.parse(stored));
        setIsDataLoading(false);
        setSyncStatus('error');
        return;
      }

      if (data) {
        const mappedBills = data.map(row => ({
          id: String(row.id),
          name: row.name,
          amount: Number(row.amount) || 0,
          dueDate: row.due_date,
          category: row.category || 'otro',
          paid: !!row.paid,
          paidAt: row.paid_at || null,
          isFixed: !!row.is_fixed,
          isInstallments: !!row.is_installments,
          totalInstallments: Number(row.total_installments) || 0,
          currentInstallment: Number(row.current_installment) || 0
        }));
        
        setBills(mappedBills);
        localStorage.setItem(storageKey(), JSON.stringify(mappedBills));
      }
      setIsDataLoading(false);
      setSyncStatus('synced');
    };

    loadData();
  }, [ownerId, houseId, storageKey]);

  // Auto-generate new month logic
  useEffect(() => {
    if (isDataLoading || bills.length === 0) return;

    const today = new Date();
    const currentMonth = today.getMonth();
    const currentYear = today.getFullYear();
    const monthKey = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}`;
    const genKey = ownerId ? `month_generated_${ownerId}_${houseId}_${monthKey}` : `month_generated_${houseId}_${monthKey}`;

    const hasBillsThisMonth = bills.some(b => {
      const d = new Date(b.dueDate + 'T12:00:00');
      return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
    });

    if (hasBillsThisMonth) {
      // Si el mes ya tiene facturas (cargadas o creadas), registramos que está inicializado
      // para evitar que se autogenere si el usuario borra todas las facturas
      localStorage.setItem(genKey, 'true');
      return;
    }

    const isMonthAlreadyGenerated = localStorage.getItem(genKey) === 'true';

    if (!hasBillsThisMonth && !isMonthAlreadyGenerated) {
      // Encontrar el último mes que tiene facturas
      const billsByMonth = {};
      bills.forEach(b => {
        const d = new Date(b.dueDate + 'T12:00:00');
        const mKey = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
        if (!billsByMonth[mKey]) billsByMonth[mKey] = [];
        billsByMonth[mKey].push(b);
      });

      const sortedMonths = Object.keys(billsByMonth).sort().reverse();
      const lastMonthKey = sortedMonths.find(m => {
        const [y, mm] = m.split('-').map(Number);
        return y < currentYear || (y === currentYear && mm - 1 < currentMonth);
      });

      if (!lastMonthKey) return;

      const lastMonthBills = billsByMonth[lastMonthKey];
      let generated = [];
      
      lastMonthBills.forEach(template => {
        // Solo clonar si NO es una cuota terminada
        const isInstallment = !!template.isInstallments;
        const total = Number(template.totalInstallments) || 0;
        const current = Number(template.currentInstallment) || 0;

        if (isInstallment && current >= total && total > 0) {
          return;
        }

        const oldDate = new Date(template.dueDate + 'T12:00:00');
        const newDate = new Date(today.getFullYear(), today.getMonth(), oldDate.getDate());
        const isoDate = newDate.toISOString().split('T')[0];

        const newItem = {
          id: crypto.randomUUID(),
          name: template.name,
          amount: (template.isFixed || isInstallment) ? Number(template.amount) : 0,
          dueDate: isoDate,
          category: template.category || 'otro',
          paid: false,
          paidAt: null,
          isFixed: !!template.isFixed,
          isInstallments: isInstallment,
          totalInstallments: total,
          currentInstallment: isInstallment ? (current + 1) : 0
        };

        generated.push(newItem);
      });
      
      if (generated.length > 0) {
        const newBills = [...bills, ...generated];
        setBills(newBills);
        setAutoGeneratedCount(generated.length);
        localStorage.setItem(storageKey(), JSON.stringify(newBills));
        localStorage.setItem(genKey, 'true');
        syncToSupabase(newBills);
      }
    }
  }, [bills, isDataLoading, ownerId, houseId, storageKey, syncToSupabase]);

  const saveBill = useCallback(async (form, isEditing) => {
    let newBills;
    if (isEditing) {
      newBills = bills.map(b => String(b.id) === String(form.id) ? { ...form, amount: Number(form.amount) } : b);
    } else {
      newBills = [...bills, { ...form, id: crypto.randomUUID(), amount: Number(form.amount), paid: false, paidAt: null }];
    }
    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));
    await syncToSupabase(newBills);
  }, [bills, storageKey, syncToSupabase]);

  const deleteService = useCallback(async (billId) => {
    const newBills = bills.filter(b => String(b.id) !== String(billId));
    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));
    await syncToSupabase(newBills);
  }, [bills, storageKey, syncToSupabase]);

  const togglePaid = useCallback(async (id) => {
    const newBills = bills.map(b => {
      if (String(b.id) === String(id) && b.amount > 0) {
        const nowPaid = !b.paid;
        return {
          ...b,
          paid: nowPaid,
          // Graba la fecha/hora exacta del pago; la borra si se desmarca
          paidAt: nowPaid ? new Date().toISOString() : null,
        };
      }
      return b;
    });
    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));
    await syncToSupabase(newBills);
  }, [bills, storageKey, syncToSupabase]);

  const signOut = useCallback(async () => {
    await supabase.auth.signOut();
  }, []);

  const value = useMemo(() => ({
    user, bills, isDataLoading, autoGeneratedCount, setAutoGeneratedCount,
    saveBill, deleteService, togglePaid, signOut, houseId, syncStatus
  }), [user, bills, isDataLoading, autoGeneratedCount, saveBill, deleteService, togglePaid, signOut, houseId, syncStatus]);

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
