import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '../lib/supabase';
import { setCustomCategoriesCache } from '../lib/utils';

const AppContext = createContext();

const SUPABASE_TABLE = 'bills';
const DEFAULT_HOUSE_ID = 'casa_1';
// HARDENING [A-1]: Patrón permitido para houseId leído desde URL.
// Previene inyección de valores arbitrarios como namespace de datos.
const ALLOWED_HOUSE_ID_PATTERN = /^[a-z0-9_-]{1,30}$/;

// ---------------------------------------------------------------------------
// sanitizeBillFromStorage — Valida y normaliza un objeto crudo desde localStorage.
// HARDENING [M-1]: Previene que datos corruptos, truncados o malformados
//   causen crashes o inyecten valores inválidos al estado de React.
//   Retorna null si el objeto no cumple los requisitos mínimos.
// ---------------------------------------------------------------------------
const sanitizeBillFromStorage = (raw) => {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
  if (!raw.id || !raw.name) return null;

  const dueDate = typeof raw.dueDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(raw.dueDate)
    ? raw.dueDate
    : null;

  return {
    id: String(raw.id),
    name: String(raw.name || '').trim().slice(0, 100),
    amount: Math.max(0, Number(raw.amount) || 0),
    dueDate,
    category: typeof raw.category === 'string'
      ? raw.category.replace(/[^a-z0-9_-]/gi, '').slice(0, 50)
      : 'otro',
    paid: !!raw.paid,
    paidAt: raw.paidAt || null,
    isFixed: !!raw.isFixed,
    isInstallments: !!raw.isInstallments,
    totalInstallments: Math.max(0, Number(raw.totalInstallments) || 0),
    currentInstallment: Math.max(0, Number(raw.currentInstallment) || 0),
  };
};



export const AppProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [ownerId, setOwnerId] = useState(null);
  // houseId se lee de la URL (?house=...) como namespace adicional.
  // La seguridad real depende del RLS de Supabase que filtra por owner_id.
  // Un mismo usuario puede tener múltiples casas usando el parámetro ?house=.
  const [houseId] = useState(() => {
    const params = new URLSearchParams(window.location.search);
    const raw = (params.get('house') || DEFAULT_HOUSE_ID).trim().toLowerCase();
    // HARDENING [A-1]: Si el valor no cumple el patrón, se usa el default seguro.
    return ALLOWED_HOUSE_ID_PATTERN.test(raw) ? raw : DEFAULT_HOUSE_ID;
  });
  const [bills, setBills] = useState([]);
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [isCheckingAuth, setIsCheckingAuth] = useState(true);
  const [autoGeneratedCount, setAutoGeneratedCount] = useState(0);
  const [syncStatus, setSyncStatus] = useState('idle');

  // Categorías personalizadas aisladas estrictamente por usuario
  const [customCategories, setCustomCategories] = useState([]);

  // Authentication logic
  useEffect(() => {
    let isMounted = true;
    let authTimeout = null;

    const finishAuthCheck = (session) => {
      if (!isMounted) return;
      if (authTimeout) {
        window.clearTimeout(authTimeout);
        authTimeout = null;
      }

      if (session && session.user) {
        setUser(session.user);
        const uid = String(session.user.id);
        setOwnerId(uid);

        // Sincronizar categorías personalizadas exclusivas de este usuario
        const cloudCategories = session.user?.user_metadata?.custom_categories;
        let userCategories = [];
        if (Array.isArray(cloudCategories)) {
          userCategories = cloudCategories;
        } else {
          try {
            const local = localStorage.getItem(`home_custom_categories_${uid}`);
            if (local) userCategories = JSON.parse(local);
          } catch {}
        }
        setCustomCategories(userCategories);
        setCustomCategoriesCache(userCategories);
        try {
          localStorage.setItem(`home_custom_categories_${uid}`, JSON.stringify(userCategories));
          // Eliminar clave global anterior que mezclaba usuarios
          localStorage.removeItem('home_custom_categories');
        } catch {}
      } else {
        setUser(null);
        setOwnerId(null);
        setBills([]);
        setCustomCategories([]);
        setCustomCategoriesCache([]);
      }
      setIsCheckingAuth(false);
    };

    const checkSession = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        finishAuthCheck(session);
      } catch (error) {
        // A network/session error must not leave the entire app on its loading screen.
        console.error('Error checking the Supabase session:', error);
        finishAuthCheck(null);
      }
    };

    // In case a network failure or stalled token refresh never settles getSession(),
    // allow the user to reach the login screen as fallback.
    authTimeout = window.setTimeout(() => {
      if (isMounted) {
        finishAuthCheck(null);
      }
    }, 5000);

    checkSession();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (!isMounted) return;

      if (event === 'SIGNED_OUT') {
        finishAuthCheck(null);
      } else if (session) {
        finishAuthCheck(session);
      } else if (event === 'INITIAL_SESSION' && !session) {
        finishAuthCheck(null);
      }
    });

    return () => {
      isMounted = false;
      if (authTimeout) {
        window.clearTimeout(authTimeout);
      }
      subscription.unsubscribe();
    };
  }, []);

  // Retorna null si no hay ownerId para evitar mezclar datos entre sesiones/usuarios
  const storageKey = useCallback(() => {
    if (!ownerId) return null;
    return `homehq_v4_${ownerId}_${houseId}`;
  }, [ownerId, houseId]);

  // ---------------------------------------------------------------------------
  // syncToSupabase — Persiste bills en Supabase.
  // HARDENING [C-2]: owner_id se OMITE del payload cliente.
  //   El servidor lo asigna via trigger enforce_owner_id() + RLS.
  //   Nunca confiar en que el cliente envíe el owner_id correcto.
  // ---------------------------------------------------------------------------
  const syncToSupabase = useCallback(async (billsToUpsert) => {
    if (!ownerId || !billsToUpsert || billsToUpsert.length === 0) return;
    setSyncStatus('syncing');

    const payload = billsToUpsert.map(b => ({
      id: String(b.id),
      // owner_id: asignado por trigger enforce_owner_id() en PostgreSQL — no enviado desde cliente
      house_id: houseId,
      name: (b.name || '').trim().slice(0, 100).replace(/[<>"'&]/g, ''),
      amount: Math.max(0, Number(b.amount) || 0),
      due_date: b.dueDate,
      category: (b.category || 'otro').replace(/[^a-z0-9_-]/gi, '').slice(0, 50),
      paid: !!b.paid,
      paid_at: b.paidAt || null,
      is_fixed: !!b.isFixed,
      is_installments: !!b.isInstallments,
      total_installments: Math.max(0, Number(b.totalInstallments) || 0),
      current_installment: Math.max(0, Number(b.currentInstallment) || 0)
    }));

    const { error: upsertError } = await supabase
      .from(SUPABASE_TABLE)
      .upsert(payload, { onConflict: 'id' });

    if (upsertError) {
      console.error('Error syncing to Supabase:', upsertError);
      setSyncStatus('error');
      return;
    }

    setSyncStatus('synced');
  }, [ownerId, houseId]);

  // Carga de servicios (modular para permitir refrescos silenciosos)
  const fetchBills = useCallback(async (isSilent = false) => {
    if (!ownerId) {
      setBills([]);
      setIsDataLoading(false);
      return;
    }

    if (!isSilent) {
      setIsDataLoading(true);
      setSyncStatus('syncing');
    }

    const { data, error } = await supabase
      .from(SUPABASE_TABLE)
      .select('*')
      .eq('owner_id', ownerId)
      .eq('house_id', houseId)
      .is('deleted_at', null)
      .order('due_date', { ascending: true });

    if (error) {
      console.error('Error loading bills:', error);
      if (!isSilent) {
        // HARDENING [M-1]: Fallback defensivo con validación de esquema.
        // Un localStorage corrupto o manipulado nunca debe crashear la app ni
        // cargar datos inválidos. Se valida cada registro antes de usarlo.
        const key = storageKey();
        if (key) {
          try {
            const stored = localStorage.getItem(key);
            if (stored) {
              const parsed = JSON.parse(stored);
              if (Array.isArray(parsed)) {
                const valid = parsed
                  .map(sanitizeBillFromStorage)
                  .filter(Boolean);
                setBills(valid);
              }
            }
          } catch (parseErr) {
            console.warn('localStorage corrupto, eliminando clave:', parseErr);
            try { localStorage.removeItem(key); } catch {}
          }
        }
        setIsDataLoading(false);
        setSyncStatus('error');
      }
      return;
    }

    if (data) {
      const mappedBills = data.map(row => ({
        id: String(row.id),
        name: row.name,
        amount: Number(row.amount) || 0,
        dueDate: row.due_date,
        category: row.category || 'otro',
        paid: !!row.paid,
        paidAt: row.paid_at || null,
        isFixed: !!row.is_fixed,
        isInstallments: !!row.is_installments,
        totalInstallments: Number(row.total_installments) || 0,
        currentInstallment: Number(row.current_installment) || 0
      }));
      
      setBills(mappedBills);
      localStorage.setItem(storageKey(), JSON.stringify(mappedBills));
    }
    if (!isSilent) {
      setIsDataLoading(false);
    }
    setSyncStatus('synced');
  }, [ownerId, houseId, storageKey]);

  // Carga inicial al autenticarse
  useEffect(() => {
    if (isCheckingAuth) return;
    fetchBills(false);
  }, [isCheckingAuth, fetchBills]);

  // Sincronización instantánea entre pestañas del mismo navegador (evento nativo storage)
  useEffect(() => {
    const handleStorage = (e) => {
      if (e.key === storageKey() && e.newValue) {
        try {
          const parsed = JSON.parse(e.newValue);
          if (Array.isArray(parsed)) {
            // HARDENING [C-1]: Validar esquema antes de actualizar el estado.
            // Previene que datos corruptos o manipulados en localStorage causen
            // crashes, montos negativos o inyecciones en el estado de React.
            const valid = parsed.map(sanitizeBillFromStorage).filter(Boolean);
            setBills(valid);
          }
        } catch {}
      }
    };
    window.addEventListener('storage', handleStorage);
    return () => window.removeEventListener('storage', handleStorage);
  }, [storageKey]);

  // Suscripción a Supabase Realtime (sincronización multi-dispositivo en vivo)
  //
  // HARDENING [M-4]: Debounce de 500ms antes de fetchBills(true).
  //   Evita que un evento Realtime llegado mientras un upsert optimista
  //   está en vuelo sobreescriba el estado local con un snapshot stale.
  //   El clearTimeout en cleanup garantiza que no queden timers huérfanos.
  useEffect(() => {
    if (!ownerId) return;

    let debounceTimer = null;

    // Canal con identificador limpio para evitar colisiones entre pestañas/sesiones
    const channelName = `realtime_bills_${ownerId}_${Date.now()}`;
    const channel = supabase
      .channel(channelName)
      .on(
        'postgres_changes',
        {
          event: '*', // INSERT, UPDATE, DELETE
          schema: 'public',
          table: SUPABASE_TABLE,
        },
        (payload) => {
          const rowOwnerId = payload.new?.owner_id || payload.old?.owner_id;
          if (!rowOwnerId || rowOwnerId === ownerId) {
            // Debounce: esperar 500ms de inactividad para evitar race condition
            // con optimistic updates locales que aún no commitearon en Supabase.
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(() => fetchBills(true), 500);
          }
        }
      )
      .subscribe();

    return () => {
      clearTimeout(debounceTimer);
      supabase.removeChannel(channel);
    };
  }, [ownerId, fetchBills]);

  // ---------------------------------------------------------------------------
  // reconcileMonthlyBills — Auto-generación granular (diff por nombre)
  //
  // DISEÑO ANTI-DUPLICACIÓN:
  //   1. Construye un Set con los nombres normalizados de las facturas que YA
  //      existen en el mes actual. Un servicio ya clonado siempre estará en el
  //      Set → nunca se duplica, sin importar cuántas veces se llame.
  //   2. Clave versionada "month_reconciled_v2_*" reemplaza a la anterior
  //      "month_generated_*" (que podía quedar envenenada). Solo se marca como
  //      'done' cuando el diff arroja 0 faltantes, garantizando que una sesión
  //      parcialmente inicializada pueda reconciliarse en la siguiente ejecución.
  //   3. Con force=true se omite la clave de control (útil desde UI para rescate
  //      manual), pero el Set sigue siendo la guarda definitiva contra duplicados.
  // ---------------------------------------------------------------------------
  // HARDENING [G-1]: Mutex para serializar ejecuciones concurrentes.
  // Previene race conditions (TOCTOU) que generarían duplicados al llamar
  // reconcileMonthlyBills({ force: true }) desde múltiples contextos en paralelo.
  const isReconciling = useRef(false);

  const reconcileMonthlyBills = useCallback(async ({ force = false } = {}) => {
    if (isReconciling.current) return;
    isReconciling.current = true;
    if (isDataLoading || bills.length === 0) {
      isReconciling.current = false;
      return;
    }

    try {
      const today = new Date();
      const currentMonth = today.getMonth();
      const currentYear = today.getFullYear();
      const monthKey = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}`;

      // v2: clave nueva para invalidar el localStorage "envenenado" de la versión anterior
      const genKey = ownerId
        ? `month_reconciled_v2_${ownerId}_${houseId}_${monthKey}`
        : `month_reconciled_v2_${houseId}_${monthKey}`;

      // Salir temprano solo si está marcado como completo Y no se fuerza la ejecución
      if (!force && localStorage.getItem(genKey) === 'done') return;

      // ── 1. Agrupar todas las facturas por mes ─────────────────────────────────
      const billsByMonth = {};
      bills.forEach(b => {
        const d = new Date(b.dueDate + 'T12:00:00');
        const mKey = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
        if (!billsByMonth[mKey]) billsByMonth[mKey] = [];
        billsByMonth[mKey].push(b);
      });

      // ── 2. Set de nombres ya presentes en el mes actual (guarda anti-duplicados) ─
      const currentMonthBills = billsByMonth[monthKey] || [];
      const existingNamesThisMonth = new Set(
        currentMonthBills.map(b => (b.name || '').trim().toLowerCase())
      );

      // ── 3. Encontrar el último mes anterior con facturas (plantilla) ──────────
      const lastMonthKey = Object.keys(billsByMonth)
        .sort()
        .reverse()
        .find(m => {
          const [y, mm] = m.split('-').map(Number);
          return y < currentYear || (y === currentYear && mm - 1 < currentMonth);
        });

      if (!lastMonthKey) {
        // No hay mes anterior: si hay facturas este mes, marcar como completo
        if (currentMonthBills.length > 0) localStorage.setItem(genKey, 'done');
        return;
      }

      // ── 4. Diff granular: clonar solo los servicios ausentes en el mes actual ─
      const daysInTargetMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
      const generated = [];

      billsByMonth[lastMonthKey].forEach(template => {
        const isInstallment = !!template.isInstallments;
        const total = Number(template.totalInstallments) || 0;
        const current = Number(template.currentInstallment) || 0;

        // Saltar cuotas ya finalizadas
        if (isInstallment && total > 0 && current >= total) return;

        // Saltar si el servicio ya existe este mes (comparación normalizada)
        const normalizedName = (template.name || '').trim().toLowerCase();
        if (existingNamesThisMonth.has(normalizedName)) return;

        // Calcular fecha destino con clamping anti-overflow (ej: 31-ene → 28-feb)
        const oldDate = new Date(template.dueDate + 'T12:00:00');
        const oldDay = isNaN(oldDate.getDate()) ? 1 : oldDate.getDate();
        const targetDay = Math.min(oldDay, daysInTargetMonth);
        const isoDate = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(targetDay).padStart(2, '0')}`;

        generated.push({
          id: crypto.randomUUID(),
          name: (template.name || '').trim(),
          // Servicios variables se clonan con amount=0 para forzar ingreso manual
          amount: (template.isFixed || isInstallment)
            ? Math.max(0, Number(template.amount) || 0)
            : 0,
          dueDate: isoDate,
          category: template.category || 'otro',
          paid: false,
          paidAt: null,
          isFixed: !!template.isFixed,
          isInstallments: isInstallment,
          totalInstallments: total,
          currentInstallment: isInstallment ? current + 1 : 0,
        });
      });

      // ── 5. Persistir solo si hay faltantes ────────────────────────────────────
      if (generated.length > 0) {
        const newBills = [...bills, ...generated];
        setBills(newBills);
        setAutoGeneratedCount(generated.length);
        localStorage.setItem(storageKey(), JSON.stringify(newBills));
        await syncToSupabase(generated);
      }

      // Marcar como completo DESPUÉS de la operación (o inmediatamente si diff=0)
      localStorage.setItem(genKey, 'done');
    } finally {
      // Liberar mutex siempre, incluso si ocurre un error inesperado
      isReconciling.current = false;
    }
  }, [bills, isDataLoading, ownerId, houseId, storageKey, syncToSupabase]);

  // Ejecución automática al cargar datos — sin force para respetar la clave de control
  useEffect(() => {
    reconcileMonthlyBills({ force: false });
  }, [reconcileMonthlyBills]);

  const saveBillsBatch = useCallback(async (billsToSave) => {
    if (!billsToSave || billsToSave.length === 0) return;
    setBills(prev => {
      let updated = [...prev];
      for (const bill of billsToSave) {
        const idx = updated.findIndex(b => String(b.id) === String(bill.id));
        if (idx >= 0) {
          updated[idx] = bill;
        } else {
          updated.push(bill);
        }
      }
      localStorage.setItem(storageKey(), JSON.stringify(updated));
      return updated;
    });
    await syncToSupabase(billsToSave);
  }, [storageKey, syncToSupabase]);

  const saveBill = useCallback(async (form, isEditing) => {
    // HARDENING [M-3]: Sanitización defensiva de campos de texto.
    // Previene XSS almacenado en notificaciones y futura renderización.
    const sanitizedAmount = Math.max(0, Number(form.amount) || 0);
    const sanitizedName = (form.name || '').trim().slice(0, 100).replace(/[<>"'&]/g, '');
    const sanitizedCategory = (form.category || 'otro').replace(/[^a-z0-9_-]/gi, '').slice(0, 50);
    let billToSync;

    if (isEditing) {
      billToSync = { ...form, name: sanitizedName, amount: sanitizedAmount, category: sanitizedCategory };
    } else {
      billToSync = {
        ...form,
        id: crypto.randomUUID(),
        name: sanitizedName,
        amount: sanitizedAmount,
        category: sanitizedCategory,
        paid: false,
        paidAt: null
      };
    }

    setBills(prev => {
      const newBills = isEditing
        ? prev.map(b => String(b.id) === String(form.id) ? billToSync : b)
        : [...prev, billToSync];
      const key = storageKey();
      if (key) localStorage.setItem(key, JSON.stringify(newBills));
      return newBills;
    });

    await syncToSupabase([billToSync]);
  }, [storageKey, syncToSupabase]);

  const deleteService = useCallback(async (billId) => {
    setBills(prev => {
      const newBills = prev.filter(b => String(b.id) !== String(billId));
      localStorage.setItem(storageKey(), JSON.stringify(newBills));
      return newBills;
    });

    if (ownerId) {
      setSyncStatus('syncing');
      const { error } = await supabase
        .from(SUPABASE_TABLE)
        .update({ deleted_at: new Date().toISOString() })
        .eq('id', String(billId))
        .eq('owner_id', ownerId);

      if (error) {
        console.error('Error al eliminar servicio en Supabase:', error);
        setSyncStatus('error');
      } else {
        setSyncStatus('synced');
      }
    }
  }, [ownerId, storageKey]);

  const togglePaid = useCallback(async (id) => {
    let updatedBill = null;
    setBills(prev => {
      const newBills = prev.map(b => {
        if (String(b.id) === String(id) && Number(b.amount) > 0) {
          const nowPaid = !b.paid;
          updatedBill = {
            ...b,
            paid: nowPaid,
            paidAt: nowPaid ? new Date().toISOString() : null,
          };
          return updatedBill;
        }
        return b;
      });
      localStorage.setItem(storageKey(), JSON.stringify(newBills));
      return newBills;
    });

    if (updatedBill) {
      await syncToSupabase([updatedBill]);
    }
  }, [storageKey, syncToSupabase]);

  const saveCustomCategories = useCallback(async (newCategories) => {
    const list = Array.isArray(newCategories) ? newCategories : [];
    setCustomCategories(list);
    setCustomCategoriesCache(list);

    if (ownerId) {
      try {
        localStorage.setItem(`home_custom_categories_${ownerId}`, JSON.stringify(list));
      } catch {}
    }

    // Sincronizar en la nube en user_metadata del usuario actual
    if (user) {
      try {
        await supabase.auth.updateUser({
          data: { custom_categories: list }
        });
      } catch (err) {
        console.warn('Error al sincronizar categorías en Supabase user_metadata:', err);
      }
    }
  }, [ownerId, user]);

  const signOut = useCallback(async () => {
    setCustomCategories([]);
    setCustomCategoriesCache([]);
    setBills([]);
    setUser(null);
    setOwnerId(null);
    await supabase.auth.signOut();
  }, []);

  const value = useMemo(() => ({
    user, bills, isDataLoading, isCheckingAuth, autoGeneratedCount, setAutoGeneratedCount,
    saveBill, saveBillsBatch, deleteService, togglePaid, signOut, houseId, syncStatus,
    customCategories, saveCustomCategories, reconcileMonthlyBills
  }), [user, bills, isDataLoading, isCheckingAuth, autoGeneratedCount, saveBill, saveBillsBatch, deleteService, togglePaid, signOut, houseId, syncStatus, customCategories, saveCustomCategories, reconcileMonthlyBills]);

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
