import React, { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';
import { supabase } from '../lib/supabase';
import { setCustomCategoriesCache } from '../lib/utils';

const AppContext = createContext();

const SUPABASE_TABLE = 'bills';
const DEFAULT_HOUSE_ID = 'casa_1';

export const AppProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [ownerId, setOwnerId] = useState(null);
  // houseId se lee de la URL (?house=...) como namespace adicional.
  // La seguridad real depende del RLS de Supabase que filtra por owner_id.
  // Un mismo usuario puede tener múltiples casas usando el parámetro ?house=.
  const [houseId] = useState(() => {
    const params = new URLSearchParams(window.location.search);
    return (params.get('house') || DEFAULT_HOUSE_ID).trim().toLowerCase();
  });
  const [bills, setBills] = useState([]);
  const [isDataLoading, setIsDataLoading] = useState(true);
  const [isCheckingAuth, setIsCheckingAuth] = useState(true);
  const [autoGeneratedCount, setAutoGeneratedCount] = useState(0);
  const [syncStatus, setSyncStatus] = useState('idle');

  // Categorías personalizadas aisladas estrictamente por usuario
  const [customCategories, setCustomCategories] = useState([]);

  // Authentication logic
  useEffect(() => {
    let isMounted = true;
    let authTimeout = null;

    const finishAuthCheck = (session) => {
      if (!isMounted) return;
      if (authTimeout) {
        window.clearTimeout(authTimeout);
        authTimeout = null;
      }

      if (session && session.user) {
        setUser(session.user);
        const uid = String(session.user.id);
        setOwnerId(uid);

        // Sincronizar categorías personalizadas exclusivas de este usuario
        const cloudCategories = session.user?.user_metadata?.custom_categories;
        let userCategories = [];
        if (Array.isArray(cloudCategories)) {
          userCategories = cloudCategories;
        } else {
          try {
            const local = localStorage.getItem(`home_custom_categories_${uid}`);
            if (local) userCategories = JSON.parse(local);
          } catch {}
        }
        setCustomCategories(userCategories);
        setCustomCategoriesCache(userCategories);
        try {
          localStorage.setItem(`home_custom_categories_${uid}`, JSON.stringify(userCategories));
          // Eliminar clave global anterior que mezclaba usuarios
          localStorage.removeItem('home_custom_categories');
        } catch {}
      } else {
        setUser(null);
        setOwnerId(null);
        setBills([]);
        setCustomCategories([]);
        setCustomCategoriesCache([]);
      }
      setIsCheckingAuth(false);
    };

    const checkSession = async () => {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        finishAuthCheck(session);
      } catch (error) {
        // A network/session error must not leave the entire app on its loading screen.
        console.error('Error checking the Supabase session:', error);
        finishAuthCheck(null);
      }
    };

    // In case a network failure or stalled token refresh never settles getSession(),
    // allow the user to reach the login screen as fallback.
    authTimeout = window.setTimeout(() => {
      if (isMounted) {
        finishAuthCheck(null);
      }
    }, 5000);

    checkSession();

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (!isMounted) return;

      if (event === 'SIGNED_OUT') {
        finishAuthCheck(null);
      } else if (session) {
        finishAuthCheck(session);
      } else if (event === 'INITIAL_SESSION' && !session) {
        finishAuthCheck(null);
      }
    });

    return () => {
      isMounted = false;
      if (authTimeout) {
        window.clearTimeout(authTimeout);
      }
      subscription.unsubscribe();
    };
  }, []);

  const storageKey = useCallback(() => {
    return ownerId ? `homehq_v4_${ownerId}_${houseId}` : `homehq_v4_${houseId}`;
  }, [ownerId, houseId]);

  // Sincronización segura de facturas a Supabase (solo sube/actualiza los registros solicitados)
  const syncToSupabase = useCallback(async (billsToUpsert) => {
    if (!ownerId || !billsToUpsert || billsToUpsert.length === 0) return;
    setSyncStatus('syncing');

    const payload = billsToUpsert.map(b => ({
      id: String(b.id),
      owner_id: ownerId,
      house_id: houseId,
      name: (b.name || '').trim(),
      amount: Math.max(0, Number(b.amount) || 0),
      due_date: b.dueDate,
      category: b.category || 'otro',
      paid: !!b.paid,
      paid_at: b.paidAt || null,
      is_fixed: !!b.isFixed,
      is_installments: !!b.isInstallments,
      total_installments: Number(b.totalInstallments) || 0,
      current_installment: Number(b.currentInstallment) || 0
    }));

    const { error: upsertError } = await supabase
      .from(SUPABASE_TABLE)
      .upsert(payload, { onConflict: 'id' });

    if (upsertError) {
      console.error('Error syncing to Supabase:', upsertError);
      setSyncStatus('error');
      return;
    }

    setSyncStatus('synced');
  }, [ownerId, houseId]);

  // Carga de servicios (modular para permitir refrescos silenciosos)
  const fetchBills = useCallback(async (isSilent = false) => {
    if (!ownerId) {
      setBills([]);
      setIsDataLoading(false);
      return;
    }

    if (!isSilent) {
      setIsDataLoading(true);
      setSyncStatus('syncing');
    }

    const { data, error } = await supabase
      .from(SUPABASE_TABLE)
      .select('*')
      .eq('owner_id', ownerId)
      .eq('house_id', houseId)
      .is('deleted_at', null)
      .order('due_date', { ascending: true });

    if (error) {
      console.error('Error loading bills:', error);
      if (!isSilent) {
        // Fallback a datos locales si Supabase falla
        try {
          const stored = localStorage.getItem(storageKey());
          if (stored) setBills(JSON.parse(stored));
        } catch (parseErr) {
          console.warn('localStorage corrupto o inválido, se ignora:', parseErr);
        }
        setIsDataLoading(false);
        setSyncStatus('error');
      }
      return;
    }

    if (data) {
      const mappedBills = data.map(row => ({
        id: String(row.id),
        name: row.name,
        amount: Number(row.amount) || 0,
        dueDate: row.due_date,
        category: row.category || 'otro',
        paid: !!row.paid,
        paidAt: row.paid_at || null,
        isFixed: !!row.is_fixed,
        isInstallments: !!row.is_installments,
        totalInstallments: Number(row.total_installments) || 0,
        currentInstallment: Number(row.current_installment) || 0
      }));
      
      setBills(mappedBills);
      localStorage.setItem(storageKey(), JSON.stringify(mappedBills));
    }
    if (!isSilent) {
      setIsDataLoading(false);
    }
    setSyncStatus('synced');
  }, [ownerId, houseId, storageKey]);

  // Carga inicial al autenticarse
  useEffect(() => {
    if (isCheckingAuth) return;
    fetchBills(false);
  }, [isCheckingAuth, fetchBills]);

  // Sincronización instantánea entre pestañas del mismo navegador (evento nativo storage)
  useEffect(() => {
    const handleStorage = (e) => {
      if (e.key === storageKey() && e.newValue) {
        try {
          const freshBills = JSON.parse(e.newValue);
          setBills(freshBills);
        } catch {}
      }
    };
    window.addEventListener('storage', handleStorage);
    return () => window.removeEventListener('storage', handleStorage);
  }, [storageKey]);

  // Suscripción a Supabase Realtime (sincronización multi-dispositivo en vivo)
  useEffect(() => {
    if (!ownerId) return;

    // Canal con identificador limpio para evitar colisiones entre pestañas/sesiones
    const channelName = `realtime_bills_${ownerId}_${Date.now()}`;
    const channel = supabase
      .channel(channelName)
      .on(
        'postgres_changes',
        {
          event: '*', // INSERT, UPDATE, DELETE
          schema: 'public',
          table: SUPABASE_TABLE,
        },
        (payload) => {
          console.log('[Supabase Realtime] Cambio detectado en bills:', payload);
          // Si el cambio afecta a este usuario o si se modificó algún servicio relevante
          const rowOwnerId = payload.new?.owner_id || payload.old?.owner_id;
          if (!rowOwnerId || rowOwnerId === ownerId) {
            fetchBills(true); // Refresco silencioso de datos
          }
        }
      )
      .subscribe((status, err) => {
        console.log(`[Supabase Realtime] Estado suscripción (${channelName}):`, status, err || '');
      });

    return () => {
      supabase.removeChannel(channel);
    };
  }, [ownerId, fetchBills]);

  // Auto-generate new month logic
  useEffect(() => {
    if (isDataLoading || bills.length === 0) return;

    const today = new Date();
    const currentMonth = today.getMonth();
    const currentYear = today.getFullYear();
    const monthKey = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}`;
    const genKey = ownerId ? `month_generated_${ownerId}_${houseId}_${monthKey}` : `month_generated_${houseId}_${monthKey}`;

    const hasBillsThisMonth = bills.some(b => {
      const d = new Date(b.dueDate + 'T12:00:00');
      return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
    });

    if (hasBillsThisMonth) {
      // Si el mes ya tiene facturas (cargadas o creadas), registramos que está inicializado
      // para evitar que se autogenere si el usuario borra todas las facturas
      localStorage.setItem(genKey, 'true');
      return;
    }

    const isMonthAlreadyGenerated = localStorage.getItem(genKey) === 'true';

    if (!hasBillsThisMonth && !isMonthAlreadyGenerated) {
      // Encontrar el último mes que tiene facturas
      const billsByMonth = {};
      bills.forEach(b => {
        const d = new Date(b.dueDate + 'T12:00:00');
        const mKey = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
        if (!billsByMonth[mKey]) billsByMonth[mKey] = [];
        billsByMonth[mKey].push(b);
      });

      const sortedMonths = Object.keys(billsByMonth).sort().reverse();
      const lastMonthKey = sortedMonths.find(m => {
        const [y, mm] = m.split('-').map(Number);
        return y < currentYear || (y === currentYear && mm - 1 < currentMonth);
      });

      if (!lastMonthKey) return;

      const lastMonthBills = billsByMonth[lastMonthKey];
      let generated = [];
      
      lastMonthBills.forEach(template => {
        // Solo clonar si NO es una cuota terminada
        const isInstallment = !!template.isInstallments;
        const total = Number(template.totalInstallments) || 0;
        const current = Number(template.currentInstallment) || 0;

        if (isInstallment && current >= total && total > 0) {
          return;
        }

        const oldDate = new Date(template.dueDate + 'T12:00:00');
        const oldDay = isNaN(oldDate.getDate()) ? 1 : oldDate.getDate();
        // Clampear al último día del mes actual para evitar desbordes (ej: 31 de enero en febrero -> 28/29)
        const daysInTargetMonth = new Date(currentYear, currentMonth + 1, 0).getDate();
        const targetDay = Math.min(oldDay, daysInTargetMonth);
        const isoDate = `${currentYear}-${String(currentMonth + 1).padStart(2, '0')}-${String(targetDay).padStart(2, '0')}`;

        const newItem = {
          id: crypto.randomUUID(),
          name: (template.name || '').trim(),
          amount: (template.isFixed || isInstallment) ? Math.max(0, Number(template.amount) || 0) : 0,
          dueDate: isoDate,
          category: template.category || 'otro',
          paid: false,
          paidAt: null,
          isFixed: !!template.isFixed,
          isInstallments: isInstallment,
          totalInstallments: total,
          currentInstallment: isInstallment ? (current + 1) : 0
        };

        generated.push(newItem);
      });
      
      if (generated.length > 0) {
        const newBills = [...bills, ...generated];
        setBills(newBills);
        setAutoGeneratedCount(generated.length);
        localStorage.setItem(storageKey(), JSON.stringify(newBills));
        localStorage.setItem(genKey, 'true');
        syncToSupabase(generated);
      }
    }
  }, [bills, isDataLoading, ownerId, houseId, storageKey, syncToSupabase]);

  const saveBill = useCallback(async (form, isEditing) => {
    const sanitizedAmount = Math.max(0, Number(form.amount) || 0);
    const sanitizedName = (form.name || '').trim();
    let newBills;
    let billToSync;

    if (isEditing) {
      billToSync = { ...form, name: sanitizedName, amount: sanitizedAmount };
      newBills = bills.map(b => String(b.id) === String(form.id) ? billToSync : b);
    } else {
      billToSync = {
        ...form,
        id: crypto.randomUUID(),
        name: sanitizedName,
        amount: sanitizedAmount,
        paid: false,
        paidAt: null
      };
      newBills = [...bills, billToSync];
    }
    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));
    await syncToSupabase([billToSync]);
  }, [bills, storageKey, syncToSupabase]);

  const deleteService = useCallback(async (billId) => {
    const newBills = bills.filter(b => String(b.id) !== String(billId));
    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));

    if (ownerId) {
      setSyncStatus('syncing');
      const { error } = await supabase
        .from(SUPABASE_TABLE)
        .update({ deleted_at: new Date().toISOString() })
        .eq('id', String(billId))
        .eq('owner_id', ownerId);

      if (error) {
        console.error('Error al eliminar servicio en Supabase:', error);
        setSyncStatus('error');
      } else {
        setSyncStatus('synced');
      }
    }
  }, [bills, ownerId, storageKey]);

  const togglePaid = useCallback(async (id) => {
    let updatedBill = null;
    const newBills = bills.map(b => {
      if (String(b.id) === String(id) && Number(b.amount) > 0) {
        const nowPaid = !b.paid;
        updatedBill = {
          ...b,
          paid: nowPaid,
          paidAt: nowPaid ? new Date().toISOString() : null,
        };
        return updatedBill;
      }
      return b;
    });

    if (!updatedBill) return;

    setBills(newBills);
    localStorage.setItem(storageKey(), JSON.stringify(newBills));
    await syncToSupabase([updatedBill]);
  }, [bills, storageKey, syncToSupabase]);

  const saveCustomCategories = useCallback(async (newCategories) => {
    const list = Array.isArray(newCategories) ? newCategories : [];
    setCustomCategories(list);
    setCustomCategoriesCache(list);

    if (ownerId) {
      try {
        localStorage.setItem(`home_custom_categories_${ownerId}`, JSON.stringify(list));
      } catch {}
    }

    // Sincronizar en la nube en user_metadata del usuario actual
    if (user) {
      try {
        await supabase.auth.updateUser({
          data: { custom_categories: list }
        });
      } catch (err) {
        console.warn('Error al sincronizar categorías en Supabase user_metadata:', err);
      }
    }
  }, [ownerId, user]);

  const signOut = useCallback(async () => {
    setCustomCategories([]);
    setCustomCategoriesCache([]);
    setBills([]);
    setUser(null);
    setOwnerId(null);
    await supabase.auth.signOut();
  }, []);

  const value = useMemo(() => ({
    user, bills, isDataLoading, isCheckingAuth, autoGeneratedCount, setAutoGeneratedCount,
    saveBill, deleteService, togglePaid, signOut, houseId, syncStatus,
    customCategories, saveCustomCategories
  }), [user, bills, isDataLoading, isCheckingAuth, autoGeneratedCount, saveBill, deleteService, togglePaid, signOut, houseId, syncStatus, customCategories, saveCustomCategories]);

  return (
    <AppContext.Provider value={value}>
      {children}
    </AppContext.Provider>
  );
};

export const useApp = () => useContext(AppContext);
