import React, { useState, useMemo, useRef, useEffect } from 'react';
import { Card, Badge, Button } from './components/ui';
import { Sidebar } from './components/layout/Sidebar';
import { HeaderMobile } from './components/layout/HeaderMobile';
import { Auth } from './components/layout/Auth';
import { BillModal } from './components/layout/BillModal';
import { PayConfirmModal } from './components/layout/PayConfirmModal';
import { DeleteConfirmModal } from './components/layout/DeleteConfirmModal';
import { InstallPromptModal } from './components/layout/InstallPromptModal';
import { Celebration } from './components/ui/Celebration';
import { DashboardView } from './components/views/DashboardView';
import { PendingView } from './components/views/PendingView';
import { HistoryView } from './components/views/HistoryView';
import { useDarkMode } from './hooks/useDarkMode';
import { useApp } from './context/AppContext';
import { formatMoney, getDiffDays } from './lib/utils';
import { disablePushNotifications, enablePushNotifications } from './lib/pushNotifications';

function App() {
  // Forzar idioma Español y desactivar traducción automática
  useEffect(() => {
    document.documentElement.lang = 'es';
    document.documentElement.setAttribute('translate', 'no');
  }, []);

  const {
    user, bills, isDataLoading, isCheckingAuth, autoGeneratedCount, setAutoGeneratedCount,
    saveBill, deleteService, togglePaid, signOut, syncStatus
  } = useApp();

  const [view, setView] = useState('dashboard');
  const [darkMode, toggleDarkMode, themeMode, setThemeMode] = useDarkMode();
  const [showBalance, setShowBalance] = useState(true);
  const containerRef = useRef(null);
  const contentRef = useRef(null);
  const [pushEnabled, setPushEnabled] = useState(() => {
    return localStorage.getItem('home_notify_enabled') === 'true';
  });

  // Modal states
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingBill, setEditingBill] = useState(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [serviceToDelete, setServiceToDelete] = useState(null);
  const [activeMenu, setActiveMenu] = useState(null);

  // Confirmación de pago
  const [payConfirmBill, setPayConfirmBill] = useState(null);

  // Presupuesto mensual (persiste en localStorage por usuario)
  const budgetKey = user ? `home_budget_${user.id}` : null;
  const [budget, setBudgetState] = useState(() => {
    if (!user) return null;
    const stored = localStorage.getItem(`home_budget_${user?.id}`);
    return stored ? Number(stored) : null;
  });

  const setBudget = (value) => {
    const num = value === '' || value === null ? null : Number(value);
    setBudgetState(num);
    if (budgetKey) {
      if (num === null) localStorage.removeItem(budgetKey);
      else localStorage.setItem(budgetKey, String(num));
    }
  };

  // Close menu on click away
  useEffect(() => {
    const handleGlobalClick = () => {
      if (activeMenu) setActiveMenu(null);
    };
    window.addEventListener('click', handleGlobalClick);
    return () => window.removeEventListener('click', handleGlobalClick);
  }, [activeMenu]);

  // Cálculos Memoizados
  const pendingBills = useMemo(() => bills.filter(b => !b.paid), [bills]);
  const pendingCount = pendingBills.length;
  const overdueCount = useMemo(() => pendingBills.filter(b => getDiffDays(b.dueDate) < 0).length, [pendingBills]);
  const paidCount = useMemo(() => bills.filter(b => b.paid).length, [bills]);

  const currentMonthBills = useMemo(() => {
    const now = new Date();
    const currMonth = now.getMonth();
    const currYear = now.getFullYear();
    return bills.filter(b => {
      const d = new Date(b.dueDate + 'T12:00:00');
      return d.getMonth() === currMonth && d.getFullYear() === currYear;
    });
  }, [bills]);

  const overdueBills = useMemo(() => {
    return pendingBills
      .filter(b => getDiffDays(b.dueDate) < 0)
      .sort((a, b) => new Date(a.dueDate + 'T12:00:00') - new Date(b.dueDate + 'T12:00:00'));
  }, [pendingBills]);

  const upcomingBills = useMemo(() => {
    return pendingBills
      .filter(b => getDiffDays(b.dueDate) >= 0)
      .sort((a, b) => new Date(a.dueDate + 'T12:00:00') - new Date(b.dueDate + 'T12:00:00'));
  }, [pendingBills]);

  const urgentBill = useMemo(() => {
    return overdueBills.length > 0 ? overdueBills[0] : (upcomingBills[0] || null);
  }, [overdueBills, upcomingBills]);

  const isOverdueAlert = overdueBills.length > 0;

  const stats = useMemo(() => {
    const monthTotal = currentMonthBills.reduce((sum, b) => sum + Number(b.amount), 0);
    const paidThisMonth = currentMonthBills.filter(b => b.paid).reduce((sum, b) => sum + Number(b.amount), 0);
    const pendingTotal = currentMonthBills.filter(b => !b.paid).reduce((sum, b) => sum + Number(b.amount), 0);
    const progress = monthTotal === 0 ? 0 : (paidThisMonth / monthTotal) * 100;

    return { 
      monthTotal, 
      pendingTotal, 
      paidThisMonth, 
      progress, 
      urgentBill,
      isOverdueAlert,
      overdueCount: overdueBills.length
    };
  }, [currentMonthBills, overdueBills, urgentBill, isOverdueAlert]);

  // Sincronizar estado real de suscripción push con el navegador al montar
  useEffect(() => {
    if ('serviceWorker' in navigator && 'PushManager' in window) {
      navigator.serviceWorker.ready.then(reg => {
        reg.pushManager.getSubscription().then(sub => {
          const isSubscribed = !!sub && Notification.permission === 'granted';
          setPushEnabled(isSubscribed);
          localStorage.setItem('home_notify_enabled', String(isSubscribed));
        }).catch(() => {});
      }).catch(() => {});
    }
  }, []);

  // Notificaciones automáticas (solo 2 días antes y el mismo día) - Antispam (1 vez al día)
  useEffect(() => {
    const notify = async () => {
      // En producción las notificaciones las envía la Edge Function programada en Supabase (Web Push)
      if (import.meta.env.PROD || !pushEnabled || bills.length === 0) return;

      const today = new Date().toISOString().split('T')[0];
      const lastNotified = localStorage.getItem('last_notified_date');
      if (lastNotified === today) return;

      try {
        let notifiedAny = false;
        const registration = await navigator.serviceWorker?.ready;

        for (const bill of pendingBills) {
          const diff = getDiffDays(bill.dueDate);

          // Avisar únicamente 2 días antes de vencer (diff === 2) o el mismo día (diff === 0)
          if (diff === 0 || diff === 2) {
            const title = diff === 0
              ? `¡Vence HOY!: ${bill.name}`
              : `Vence en 2 días: ${bill.name}`;
            const body = bill.amount > 0
              ? `El servicio ${bill.name} por ${formatMoney(bill.amount)} vence ${diff === 0 ? 'hoy' : 'en 2 días'}.`
              : `El servicio ${bill.name} vence ${diff === 0 ? 'hoy' : 'en 2 días'}.`;

            if (registration && 'showNotification' in registration) {
              await registration.showNotification(title, {
                body,
                icon: '/logo-notificacion.png',
                badge: '/logo-notificacion.png',
                vibrate: [200, 100, 200]
              });
            } else if ('Notification' in window && Notification.permission === 'granted') {
              new Notification(title, { body, icon: '/logo-notificacion.png' });
            }
            notifiedAny = true;
          }
        }

        if (notifiedAny) {
          localStorage.setItem('last_notified_date', today);
        }
      } catch (err) {
        console.error('Error al enviar notificación:', err);
      }
    };

    notify();
  }, [pushEnabled, bills, pendingBills]);

  const toggleNotifications = async () => {
    try {
      const message = pushEnabled
        ? await disablePushNotifications()
        : await enablePushNotifications();

      // Mostrar el mensaje primero, luego actualizar el estado local
      window.alert(message);
      const nextValue = !pushEnabled;
      setPushEnabled(nextValue);
      localStorage.setItem('home_notify_enabled', String(nextValue));
    } catch (err) {
      console.error('Error al configurar notificaciones:', err);
      window.alert(err.message || 'No se pudieron configurar las notificaciones.');
    }
  };

  const handleEdit = (bill) => {
    setEditingBill(bill);
    setIsModalOpen(true);
  };

  const handleDeleteClick = (bill) => {
    setServiceToDelete(bill);
    setShowDeleteConfirm(true);
  };

  const executeDelete = () => {
    if (serviceToDelete) {
      deleteService(serviceToDelete.id);
      setShowDeleteConfirm(false);
      setServiceToDelete(null);
    }
  };

  const handleTogglePaid = (bill) => {
    if (Number(bill.amount) <= 0) {
      // Sin monto: abre el editor para que complete el valor
      handleEdit(bill);
      return;
    }
    // Tanto al marcar como pagado como al volver a poner como impago, solicita confirmación
    setPayConfirmBill(bill);
  };

  const confirmPay = () => {
    if (payConfirmBill) togglePaid(payConfirmBill.id);
    setPayConfirmBill(null);
  };


  // FIX: antes era (isDataLoading && user), lo que dejaba un hueco donde
  // user=null hacía falsa la condición y mostraba Login/contenido vacío
  // provocando el flash de "¡Todo al día!" antes de cargar los bills.
  // isDataLoading ya se pone en false cuando no hay usuario (AppContext),
  // por lo que la guarda && user es innecesaria y peligrosa.
  if (isCheckingAuth || isDataLoading) {
    return (
      <div className="h-dvh w-full bg-slate-50 dark:bg-slate-900 text-slate-700 dark:text-slate-200 flex items-center justify-center transition-opacity duration-500 relative">
        <div className="text-center relative z-10 page-enter">
          <img src="/logo-home.png" alt="Home" className="w-20 h-20 rounded-[1.25rem] mx-auto mb-6 float-gentle shadow-2xl" />
          <p className="font-bold tracking-widest uppercase text-xs animate-pulse">Cargando...</p>
        </div>
      </div>
    );
  }
  if (!user) return <Auth />;

  const getPageTitle = () => {
    switch(view) {
      case 'dashboard': return 'General';
      case 'pending': return 'Pendientes';
      case 'history': return 'Historial';
      default: return 'Inicio';
    }
  };

  const getPageSubtitle = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('es-AR', { weekday: 'long', day: 'numeric', month: 'long' });
    switch(view) {
      case 'dashboard': return dateStr;
      case 'pending': return 'Ordenado por lo que vence antes.';
      case 'history': return 'Registro real de tus movimientos pasados.';
      default: return '';
    }
  };

  return (
    <div className="h-dvh flex flex-col md:flex-row text-slate-800 dark:text-slate-100 transition-colors overflow-hidden">
      <Sidebar
        view={view}
        setView={setView}
        pendingCount={pendingCount}
        overdueCount={overdueCount}
        paidCount={paidCount}
        calculateMonthTotal={() => stats.monthTotal}
        formatMoney={formatMoney}
        darkMode={darkMode}
        toggleDarkMode={toggleDarkMode}
        themeMode={themeMode}
        setThemeMode={setThemeMode}
        showBalance={showBalance}
        user={user}
        signOut={signOut}
        syncStatus={syncStatus}
        pushEnabled={pushEnabled}
        toggleNotifications={toggleNotifications}
      />

      <main className="flex-1 flex flex-col relative w-full h-full overflow-hidden">
        <HeaderMobile
          toggleBalance={() => setShowBalance(!showBalance)}
          showBalance={showBalance}
          darkMode={darkMode}
          toggleDarkMode={toggleDarkMode}
          themeMode={themeMode}
          setThemeMode={setThemeMode}
          signOut={signOut}
          user={user}
          pushEnabled={pushEnabled}
          requestPushPermission={toggleNotifications}
          syncStatus={syncStatus}
        />

        <div key={view} className="flex-1 p-3.5 sm:p-4 md:p-10 pt-[4.9rem] sm:pt-20 md:pt-10 overflow-y-auto page-enter" style={{ paddingTop: 'calc(4.9rem + env(safe-area-inset-top, 0px))', WebkitOverflowScrolling: 'touch' }}>
          <div className="max-w-5xl mx-auto space-y-3 sm:space-y-6 pb-32">

            <div className="flex flex-col md:flex-row md:items-end justify-between gap-1 sm:gap-4 mb-1.5 sm:mb-4">
              <div>
                <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">{getPageTitle()}</h2>
                <p className="text-slate-500 dark:text-slate-400 font-medium text-xs sm:text-sm md:text-base capitalize">{getPageSubtitle()}</p>
              </div>
              {view === 'dashboard' && (
                <Button className="hidden md:flex" icon="fa-solid fa-plus" onClick={() => { setEditingBill(null); setIsModalOpen(true); }}>
                  Nuevo Servicio
                </Button>
              )}
            </div>

            {autoGeneratedCount > 0 && (
              <div className="bg-blue-50 dark:bg-blue-500/10 border border-blue-100 dark:border-blue-500/20 p-4 rounded-xl flex items-center justify-between shadow-sm mb-6">
                <div className="flex items-center gap-3">
                  <div className="bg-blue-100 dark:bg-blue-500/20 text-blue-600 dark:text-blue-400 w-10 h-10 rounded-full flex items-center justify-center">
                    <i className="fa-solid fa-wand-magic-sparkles"></i>
                  </div>
                  <div>
                    <p className="font-bold text-blue-900 dark:text-blue-100">¡Nuevo mes detectado!</p>
                    <p className="text-sm text-blue-700 dark:text-blue-300">Se copiaron <span className="font-bold">{autoGeneratedCount}</span> servicios. Define los montos.</p>
                  </div>
                </div>
                <button onClick={() => setAutoGeneratedCount(0)} className="text-blue-500 hover:text-blue-800 transition"><i className="fa-solid fa-xmark"></i></button>
              </div>
            )}

            {/* Vistas Principales */}
            {view === 'dashboard' && (
              <DashboardView
                bills={currentMonthBills}
                allBills={bills}
                showBalance={showBalance}
                calculatePendingTotal={() => stats.pendingTotal}
                calculatePaidThisMonth={() => stats.paidThisMonth}
                currentMonthProgress={() => stats.progress}
                getNextDueBill={() => stats.urgentBill}
                urgentBill={stats.urgentBill}
                isOverdueAlert={stats.isOverdueAlert}
                overdueCount={stats.overdueCount}
                handleEdit={handleEdit}
                handleDeleteClick={handleDeleteClick}
                handleTogglePaid={handleTogglePaid}
                activeMenu={activeMenu}
                setActiveMenu={setActiveMenu}
                budget={budget}
                onSetBudget={setBudget}
                monthTotal={stats.monthTotal}
              />
            )}

            {view === 'pending' && (
              <PendingView
                bills={pendingBills}
                hasBillsThisMonth={currentMonthBills.length > 0}
                handleEdit={handleEdit}
                handleDeleteClick={handleDeleteClick}
                handleTogglePaid={handleTogglePaid}
                activeMenu={activeMenu}
                setActiveMenu={setActiveMenu}
                showBalance={showBalance}
              />
            )}

            {view === 'history' && (
              <HistoryView
                bills={bills}
                handleEdit={handleEdit}
                showBalance={showBalance}
              />
            )}
          </div>
        </div>

        {/* Gradiente hacia arriba: sutil fade justo detrás de la nav flotante sin invadir las tarjetas */}
        <div 
          className="md:hidden fixed bottom-0 left-0 right-0 bg-gradient-to-t from-slate-50/90 dark:from-slate-900/90 to-transparent pointer-events-none z-30 transition-colors duration-300"
          style={{ height: 'calc(4.5rem + env(safe-area-inset-bottom, 0px))' }}
        />

        {/* Mobile Navigation — píldora flotante 100% simétrica */}
        <nav 
          className="md:hidden fixed left-1/2 -translate-x-1/2 w-[92%] max-w-sm bg-slate-50 dark:bg-slate-900 rounded-[2.5rem] p-1.5 flex items-center z-40 shadow-[0_4px_24px_rgba(0,0,0,0.10)] dark:shadow-[0_4px_24px_rgba(0,0,0,0.50)] border border-slate-200 dark:border-white/10 transition-colors duration-300"
          style={{ bottom: 'calc(1.5rem + env(safe-area-inset-bottom, 0px))' }}
        >
          <div className="grid grid-cols-3 w-full items-center">
            {[
              { id: 'dashboard', icon: 'fa-chart-pie', label: 'Inicio' },
              { id: 'pending', icon: 'fa-clock', label: 'Pendientes' },
              { id: 'history', icon: 'fa-receipt', label: 'Historial' }
            ].map(item => (
              <button
                key={item.id}
                onClick={() => setView(item.id)}
                className={`relative flex flex-col items-center justify-center gap-1 py-2 px-2 transition-all duration-300 rounded-[2rem] ${
                  view === item.id 
                    ? 'text-blue-600 dark:text-blue-400 bg-blue-50/80 dark:bg-white/10 shadow-inner' 
                    : 'text-slate-600 dark:text-slate-300 hover:text-blue-500 dark:hover:text-white'
                }`}
              >
                <i className={`fa-solid ${item.icon} text-xl`}></i>
                {item.id === 'pending' && pendingCount > 0 && (
                  <div className="absolute top-2 right-6 w-2 h-2 bg-red-500 rounded-full border border-slate-50 dark:border-slate-900 shadow-sm animate-pulse"></div>
                )}
                <span className={`text-[9px] font-black uppercase tracking-widest leading-none ${view === item.id ? 'opacity-100' : 'opacity-70'}`}>
                  {item.label}
                </span>
              </button>
            ))}
          </div>
        </nav>

        {/* Botón de acción flotante (FAB) despegado en la esquina inferior derecha, por encima del nav (estilo app de referencia) */}
        <button
          onClick={() => { setEditingBill(null); setIsModalOpen(true); }}
          className="md:hidden fixed right-5 w-14 h-14 bg-gradient-to-tr from-blue-600 to-blue-500 text-white rounded-full flex items-center justify-center shadow-[0_8px_25px_rgba(37,99,235,0.45)] active:scale-90 hover:scale-105 transition-all z-40 border border-white/25"
          style={{ bottom: 'calc(6.25rem + env(safe-area-inset-bottom, 0px))' }}
          aria-label="Agregar servicio"
          title="Agregar servicio"
        >
          <i className="fa-solid fa-plus text-2xl"></i>
        </button>
      </main>

      <BillModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={saveBill}
        bill={editingBill}
      />

      <PayConfirmModal
        bill={payConfirmBill}
        onConfirm={confirmPay}
        onClose={() => setPayConfirmBill(null)}
      />

      <DeleteConfirmModal
        isOpen={showDeleteConfirm}
        bill={serviceToDelete}
        onConfirm={executeDelete}
        onClose={() => {
          setShowDeleteConfirm(false);
          setServiceToDelete(null);
        }}
      />

      <InstallPromptModal />
    </div>
  );
}

export default App;
