import React, { useState, useMemo, useRef, useEffect } from 'react';
import { Card, Badge, Button } from './components/ui';
import { Sidebar } from './components/layout/Sidebar';
import { HeaderMobile } from './components/layout/HeaderMobile';
import { Auth } from './components/layout/Auth';
import { BillModal } from './components/layout/BillModal';
import { Celebration } from './components/ui/Celebration';
import { DashboardView } from './components/views/DashboardView';
import { PendingView } from './components/views/PendingView';
import { HistoryView } from './components/views/HistoryView';
import { useDarkMode } from './hooks/useDarkMode';
import { useApp } from './context/AppContext';
import { formatMoney, getDiffDays } from './lib/utils';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';

gsap.registerPlugin(useGSAP);

function App() {
  // Forzar idioma Español y desactivar traducción automática
  useEffect(() => {
    document.documentElement.lang = 'es';
    document.documentElement.setAttribute('translate', 'no');
  }, []);

  const { 
    user, bills, isDataLoading, autoGeneratedCount, setAutoGeneratedCount,
    saveBill, deleteService, togglePaid, signOut 
  } = useApp();
  
  const [view, setView] = useState('dashboard');
  const [darkMode, toggleDarkMode] = useDarkMode();
  const [showBalance, setShowBalance] = useState(true);
  const containerRef = useRef(null);
  const contentRef = useRef(null);
  const [pushEnabled, setPushEnabled] = useState(() => {
    return localStorage.getItem('home_notify_enabled') === 'true';
  });
  
  // Modal states
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingBill, setEditingBill] = useState(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [serviceToDelete, setServiceToDelete] = useState(null);
  const [activeMenu, setActiveMenu] = useState(null);

  // Close menu on click away
  useEffect(() => {
    const handleGlobalClick = () => {
      if (activeMenu) setActiveMenu(null);
    };
    window.addEventListener('click', handleGlobalClick);
    return () => window.removeEventListener('click', handleGlobalClick);
  }, [activeMenu]);

  // View Transitions
  useGSAP(() => {
    if (!contentRef.current) return;
    
    const tl = gsap.timeline();
    tl.fromTo(contentRef.current, 
      { opacity: 0.5, y: 10 },
      { opacity: 1, y: 0, duration: 0.3, ease: 'power2.out', clearProps: 'all' }
    );

    // Capturar todas las tarjetas y elementos interactivos para la "onda"
    const cards = contentRef.current.querySelectorAll('.glass-card, .celebration-trigger, .bill-card-item, .card-ui');
    if (cards.length > 0) {
      tl.from(cards, {
        opacity: 0,
        y: 20,
        stagger: 0.06, // Aumentado para que se note la onda de arriba a abajo
        duration: 0.4,
        ease: 'power2.out',
        clearProps: 'all'
      }, "-=0.2");
    }

  }, { dependencies: [view], scope: containerRef });

  // Cálculos Memoizados
  const pendingBills = useMemo(() => bills.filter(b => !b.paid), [bills]);
  const pendingCount = pendingBills.length;
  
  const currentMonthBills = useMemo(() => {
    const now = new Date();
    const currMonth = now.getMonth();
    const currYear = now.getFullYear();
    return bills.filter(b => {
      const d = new Date(b.dueDate + 'T12:00:00');
      return d.getMonth() === currMonth && d.getFullYear() === currYear;
    });
  }, [bills]);

  const stats = useMemo(() => {
    const monthTotal = currentMonthBills.reduce((sum, b) => sum + Number(b.amount), 0);
    const paidThisMonth = currentMonthBills.filter(b => b.paid).reduce((sum, b) => sum + Number(b.amount), 0);
    const pendingTotal = currentMonthBills.filter(b => !b.paid).reduce((sum, b) => sum + Number(b.amount), 0);
    const progress = monthTotal === 0 ? 0 : (paidThisMonth / monthTotal) * 100;
    
    const nextDue = pendingBills
      .filter(b => getDiffDays(b.dueDate) >= 0)
      .sort((a, b) => new Date(a.dueDate) - new Date(b.dueDate))[0];

    return { monthTotal, pendingTotal, paidThisMonth, progress, nextDue };
  }, [currentMonthBills, pendingBills]);

  // Notificaciones (2, 1 y 0 días) - Antispam (1 vez al día)
  useEffect(() => {
    const notify = async () => {
      if (!pushEnabled || bills.length === 0) return;
      
      const today = new Date().toISOString().split('T')[0];
      const lastNotified = localStorage.getItem('last_notified_date');
      if (lastNotified === today) return;

      try {
        let notifiedAny = false;
        const registration = await navigator.serviceWorker?.ready;

        for (const bill of pendingBills) {
          if (bill.amount <= 0) continue;
          const diff = getDiffDays(bill.dueDate);
          
          if (diff >= 0 && diff <= 2) {
            const title = diff === 0 ? `¡Vence HOY!: ${bill.name}` : `Vencimiento en ${diff} ${diff === 1 ? 'día' : 'días'}: ${bill.name}`;
            const body = `El servicio ${bill.name} por ${formatMoney(bill.amount)} vence pronto.`;

            if (registration && 'showNotification' in registration) {
              await registration.showNotification(title, {
                body,
                icon: '/logo-notificacion.png',
                badge: '/logo-notificacion.png',
                vibrate: [200, 100, 200]
              });
            } else if ('Notification' in window && Notification.permission === 'granted') {
              new Notification(title, { body, icon: '/logo-notificacion.png' });
            }
            notifiedAny = true;
          }
        }

        if (notifiedAny) {
          localStorage.setItem('last_notified_date', today);
        }
      } catch (err) {
        console.error("Error al enviar notificación:", err);
      }
    };

    notify();
  }, [pushEnabled, bills, pendingBills]);

  const toggleNotifications = async () => {
    if (pushEnabled) {
      setPushEnabled(false);
      localStorage.setItem('home_notify_enabled', 'false');
      return;
    }

    try {
      if ('Notification' in window) {
        const permission = await Notification.requestPermission();
        if (permission === 'granted') {
          setPushEnabled(true);
          localStorage.setItem('home_notify_enabled', 'true');
          
          const registration = await navigator.serviceWorker?.ready;
          const title = "Home - Servicios";
          const options = {
            body: "¡Notificaciones activadas! Te avisaremos cuando falten 2, 1 o 0 días para vencer.",
            icon: "/logo-notificacion.png",
            badge: "/logo-notificacion.png"
          };

          if (registration && 'showNotification' in registration) {
            registration.showNotification(title, options);
          } else {
            new Notification(title, options);
          }
        }
      }
    } catch (err) {
      console.error("Error al activar notificaciones:", err);
      // Fallback: al menos activar el estado local si el error fue solo visual
      setPushEnabled(true);
      localStorage.setItem('home_notify_enabled', 'true');
    }
  };

  const handleEdit = (bill) => {
    setEditingBill(bill);
    setIsModalOpen(true);
  };

  const handleDeleteClick = (bill) => {
    setServiceToDelete(bill);
    setShowDeleteConfirm(false); // Reset first
    setTimeout(() => setShowDeleteConfirm(true), 10);
  };

  const executeDelete = () => {
    if (serviceToDelete) {
      deleteService(serviceToDelete.name);
      setShowDeleteConfirm(false);
      setServiceToDelete(null);
    }
  };

  const handleTogglePaid = (bill) => {
    if (Number(bill.amount) > 0) {
      togglePaid(bill.id);
    } else {
      handleEdit(bill);
    }
  };

  if (!user && !isDataLoading) return <Auth />;
  if (isDataLoading && !user) {
    return (
      <div className="h-screen w-full bg-slate-900 flex items-center justify-center">
        <div className="w-10 h-10 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin"></div>
      </div>
    );
  }

  const getPageTitle = () => {
    switch(view) {
      case 'dashboard': return 'General';
      case 'pending': return 'Pendientes';
      case 'history': return 'Historial';
      default: return 'Inicio';
    }
  };

  const getPageSubtitle = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('es-AR', { weekday: 'long', day: 'numeric', month: 'long' });
    switch(view) {
      case 'dashboard': return dateStr;
      case 'pending': return 'Ordenado por lo que vence antes.';
      case 'history': return 'Registro real de tus movimientos pasados.';
      default: return '';
    }
  };

  return (
    <div className="h-screen flex flex-col md:flex-row bg-slate-50 dark:bg-slate-900 text-slate-800 dark:text-slate-100 transition-colors overflow-hidden">
      <Sidebar 
        view={view} 
        setView={setView} 
        pendingCount={pendingCount}
        calculateMonthTotal={() => stats.monthTotal}
        formatMoney={formatMoney}
        darkMode={darkMode}
        toggleDarkMode={toggleDarkMode}
        showBalance={showBalance}
        signOut={signOut}
        user={user}
      />
      
      <main ref={containerRef} className="flex-1 flex flex-col relative w-full h-full overflow-y-auto scroll-smooth">
        <HeaderMobile 
          view={view}
          getPageTitle={getPageTitle}
          toggleBalance={() => setShowBalance(!showBalance)}
          showBalance={showBalance}
          darkMode={darkMode}
          toggleDarkMode={toggleDarkMode}
          openModal={() => { setEditingBill(null); setIsModalOpen(true); }}
          signOut={signOut}
          user={user}
          pushEnabled={pushEnabled}
          requestPushPermission={toggleNotifications}
        />

        <div ref={contentRef} className="flex-1 p-4 md:p-10 pt-20 md:pt-10">
          <div className="max-w-5xl mx-auto space-y-6 pb-32">
            
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-4">
              <div>
                <h2 className="text-2xl md:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">{getPageTitle()}</h2>
                <p className="text-slate-500 dark:text-slate-400 font-medium text-sm md:text-base capitalize">{getPageSubtitle()}</p>
              </div>
              {view === 'dashboard' && (
                <Button className="hidden md:flex" icon="fa-solid fa-plus" onClick={() => { setEditingBill(null); setIsModalOpen(true); }}>
                  Nuevo Servicio
                </Button>
              )}
            </div>

            {autoGeneratedCount > 0 && (
              <div className="bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-100 dark:border-indigo-500/20 p-4 rounded-xl flex items-center justify-between shadow-sm mb-6">
                <div className="flex items-center gap-3">
                  <div className="bg-indigo-100 dark:bg-indigo-500/20 text-indigo-600 dark:text-indigo-400 w-10 h-10 rounded-full flex items-center justify-center">
                    <i className="fa-solid fa-wand-magic-sparkles"></i>
                  </div>
                  <div>
                    <p className="font-bold text-indigo-900 dark:text-indigo-100">¡Nuevo mes detectado!</p>
                    <p className="text-sm text-indigo-700 dark:text-indigo-300">Se copiaron <span className="font-bold">{autoGeneratedCount}</span> servicios. Define los montos.</p>
                  </div>
                </div>
                <button onClick={() => setAutoGeneratedCount(0)} className="text-indigo-500 hover:text-indigo-800 transition"><i className="fa-solid fa-xmark"></i></button>
              </div>
            )}

            {/* Vistas Principales */}
            {view === 'dashboard' && (
              <DashboardView 
                  bills={currentMonthBills}
                  allBills={bills}
                  showBalance={showBalance}
                  calculatePendingTotal={() => stats.pendingTotal}
                  calculatePaidThisMonth={() => stats.paidThisMonth}
                  currentMonthProgress={() => stats.progress}
                  getNextDueBill={() => stats.nextDue}
                  handleEdit={handleEdit}
                  handleDeleteClick={handleDeleteClick}
                  handleTogglePaid={handleTogglePaid}
                  activeMenu={activeMenu}
                  setActiveMenu={setActiveMenu}
                />
            )}

            {view === 'pending' && (
              <PendingView 
                bills={pendingBills}
                hasBillsThisMonth={currentMonthBills.length > 0}
                handleEdit={handleEdit}
                handleDeleteClick={handleDeleteClick}
                handleTogglePaid={handleTogglePaid}
                activeMenu={activeMenu}
                setActiveMenu={setActiveMenu}
              />
            )}

            {view === 'history' && (
              <HistoryView 
                bills={bills}
                handleEdit={handleEdit}
              />
            )}
          </div>
        </div>
        
        {/* Mobile Navigation */}
        <nav className="md:hidden fixed bottom-6 left-1/2 -translate-x-1/2 w-[92%] max-w-sm bg-white/60 dark:bg-slate-900/70 backdrop-blur-2xl rounded-[2.5rem] p-1.5 flex items-center justify-between z-40 shadow-[0_25px_60px_rgba(0,0,0,0.15)] dark:shadow-[0_25px_60px_rgba(0,0,0,0.5)] border border-slate-200/50 dark:border-white/10 transition-all duration-500">
          <div className="flex flex-1 items-center justify-around pr-2">
            {[
              { id: 'dashboard', icon: 'fa-chart-pie', label: 'Inicio' },
              { id: 'pending', icon: 'fa-clock', label: 'Pagos' },
              { id: 'history', icon: 'fa-receipt', label: 'Historial' }
            ].map(item => (
              <button 
                key={item.id}
                onClick={() => setView(item.id)}
                className={`relative flex flex-col items-center gap-1 px-4 py-2.5 transition-all duration-300 rounded-[2.1rem] ${view === item.id ? 'text-indigo-600 dark:text-indigo-400 bg-indigo-50/80 dark:bg-white/10 shadow-inner' : 'text-slate-400 dark:text-slate-300 hover:text-indigo-500 dark:hover:text-white'}`}
              >
                <i className={`fa-solid ${item.icon} text-xl`}></i>
                {item.id === 'pending' && pendingCount > 0 && (
                  <div className="absolute top-2.5 right-4 w-2 h-2 bg-red-500 rounded-full border border-white dark:border-slate-900 shadow-sm animate-pulse"></div>
                )}
                <span className={`text-[9px] font-black uppercase tracking-widest leading-none ${view === item.id ? 'opacity-100' : 'opacity-60'}`}>{item.label}</span>
              </button>
            ))}
          </div>
          <div className="w-px h-8 bg-slate-200 dark:bg-white/10 mx-1"></div>
          <button 
            onClick={() => { setEditingBill(null); setIsModalOpen(true); }}
            className="w-14 h-14 bg-indigo-600 dark:bg-indigo-500 text-white rounded-[1.75rem] flex items-center justify-center shadow-xl shadow-indigo-500/30 active:scale-90 transition-all ml-1 border border-white/20"
          >
            <i className="fa-solid fa-plus text-xl"></i>
          </button>
        </nav>
      </main>

      <BillModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)} 
        onSave={saveBill} 
        bill={editingBill} 
      />

      {showDeleteConfirm && (
        <div className="fixed inset-0 z-[110] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-slate-900/40 backdrop-blur-md" onClick={() => setShowDeleteConfirm(false)}></div>
          <Card className="w-full max-w-sm p-8 text-center relative z-50 border border-white/20 bg-white/70 dark:bg-slate-900/70 backdrop-blur-2xl shadow-2xl animate-in zoom-in-95 duration-200 !rounded-[2.5rem]">
              <div className="w-20 h-20 bg-white/50 dark:bg-white/10 text-red-500 rounded-3xl mx-auto flex items-center justify-center mb-6 text-3xl shadow-xl shadow-red-500/10 border border-red-500/10">
                <i className="fa-solid fa-trash-can"></i>
              </div>
              <h3 className="text-2xl font-black text-slate-800 dark:text-white mb-2 tracking-tight">¿Eliminar servicio?</h3>
              <p className="text-indigo-600 dark:text-indigo-400 font-black text-lg mb-2 uppercase tracking-tight">{serviceToDelete?.name}</p>
              <p className="text-slate-500 dark:text-slate-400 text-sm font-medium mb-8 leading-relaxed">Se eliminarán los pagos de este mes. El historial de meses pasados se mantendrá intacto.</p>
              <div className="flex gap-4">
                <Button variant="ghost" className="flex-1 !rounded-2xl font-bold py-4 hover:bg-slate-100/50" onClick={() => setShowDeleteConfirm(false)}>Cancelar</Button>
                <Button variant="danger" className="flex-1 !rounded-2xl font-black py-4 shadow-lg shadow-red-500/20" onClick={executeDelete}>Eliminar</Button>
              </div>
          </Card>
        </div>
      )}
    </div>
  );
}

export default App;
